### ISSUE TITLE
TypeError when using Webpack 5

### ISSUE THREAD

**Issue by OskarPersson** [rbarilani/remove-source-map-url-webpack-plugin#5]
When I use this plugin with Webpack 5 I get the following error:

```
TypeError: compiler.plugin is not a function
```

**Comment by rbarilani** [comment]
Hi @OskarPersson, thanks for reporting. I didn't test the plugin yet with webpack version 5, the problem might be related to a breaking change introduced in the new major version (see https://webpack.js.org/blog/2020-10-10-webpack-5-release/ and https://webpack.js.org/migrate/5/). 
As soon as I can I will have a look.

**Comment by rbarilani** [comment]
Hi @OskarPersson can you check to install the next version? The next version should address the issue by supporting webpack 5.

```
npm install @rbarilani/remove-source-map-url-webpack-plugin@next --save-dev
```

**Comment by OskarPersson** [comment]
Works great, thanks!
